---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: admission-portal
  namespace: K8S_NAMESPACE  
  labels:
    app: admission-portal
spec:
  replicas: 1
  selector:
    matchLabels:
      app: admission-portal
  template:
    metadata:
      labels:
        app: admission-portal
    spec:
      containers:
        - name: admission-portal
          image: CONTAINER_IMAGE
          ports:
            - containerPort: 80
      tolerations:
        - key: "agentpool"
          operator: "Equal"
          value: "application"
          effect: "NoSchedule"
---
apiVersion: v1
kind: Service
metadata:
  name: admission-portal
  namespace: K8S_NAMESPACE  
spec:
  selector:
    app: admission-portal
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80