apiVersion: apps/v1
kind: Deployment
metadata:
  name: ken42-aws-devops-deployment
  labels:
    app: ken42-aws-devops
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ken42-aws-devops
  template:
    metadata:
      labels:
        app: ken42-aws-devops
    spec:
      containers:
        - name: ken42-aws-devops
          image: 268117265615.dkr.ecr.ap-south-1.amazonaws.com/ken42-aws-devops:2023-04-27.06.00.33.68735052
          ports:
            - containerPort: 80