apiVersion: v1
kind: Service
metadata:
  name: admission-portal
  namespace: K8S_NAMESPACE  
spec:
  selector:
    app: admission-portal
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80