apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/proxy-body-size: 750m
    nginx.ingress.kubernetes.io/proxy-buffer-size: 750k
    nginw.ingress.kubernetes.io/rewrite-target: /
  name: eks-devops-ingress-service
  namespace: K8S_NAMESPACE
spec:
  ingressClassName: nginx
  rules:
  - host: nasscom-sample.ken42.com
    http:
      paths:
      - backend:
          service:
             name: ken42-aws-devops-nodeport-service
             port:
              number: 80
        path: /
        pathType: ImplementationSpecific
  tls:
  - hosts:
    - nasscom-sample.ken42.com
    secretName: tls-secret
