apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/proxy-body-size: 750m
    nginx.ingress.kubernetes.io/proxy-buffer-size: 750k
    nginw.ingress.kubernetes.io/rewrite-target: /
  name: nasscom-stage-aws-ingress
  namespace: nasscom-stage
spec:
  rules:
  - host: nasscom-stage-aws.ken42.org
    http:
      paths:
      - backend:
          service:
             name: admission-portal
             port:
              number: 80
        path: /
        pathType: ImplementationSpecific
  tls:
  - hosts:
    - nasscom-stage-aws.ken42.org
    secretName: tls-secret
